name: essentialsTP
main: essentialsTP\essentialsTP
version: 1.2.3
api: [3.0.0]
extensions: [sqlite3]
commands:
 tpa:
  description: Send teleport request to player to teleport you to player.
  usage: "/tpa <player>"
  permission: essentialstp.command.tpa
 tpahere:
  description: Send teleport request to teleport player to you.
  usage: "/tpahere <player>"
  permission: essentialstp.command.tpahere
 tpaccept:
  description: Accept a teleport request.
  usage: "/tpaccept"
  permission: essentialstp.command.tpaccept
 tpdeny:
   description: decline all active teleport requests.
   usage: "/tpdeny"
   permission: essentialstp.command.tpdeny
permissions:
 essentialstp.*:
  default: op
  description: "Allows all essentialsTP commands"
  children:
   essentialstp.command.*:
    description: "Allows player to use commands"
    default: op
    children:
     essentialstp.command.tpdeny:
      description: "Allows player to decline request"
      default: true
     essentialstp.command.tpaccept:
      description: "Allows player to accept request"
      default: true
     essentialstp.command.tpahere:
      description: "Allows player to teleport player to them"
      default: true
     essentialstp.command.tpa:
      description: "Allows player to teleport to another player"
      default: true