---
plugin-name: JustTP
sqlite-dbname: just_tp
tpa-here-cooldown: "30"
tp-home-cooldown: "5"
tp-warp-cooldown: "5"
tp-spawn-cooldown: "5"
Lang_invalid_usage: 'INVALID USAGE:'
Lang_command_only_use_ingame: This command can only be used in the game.
Lang_no_permissions: '[JustTP] No permission.'
Lang_teleport_home: Teleported you home.
Lang_teleport_spawn: Teleported you to spawn.
Lang_teleport_wild: Teleported you some where wild.
Lang_teleport_death: Teleported to last death cords.
Lang_no_teleport_self: You cant teleport to your self.
Lang_player_not_online: Player is not online.
Lang_sent_request_you: sent a request to teleport to you.
Lang_sent_request_them: sent a request to you, to teleport to them.
Lang_accept_request: to accept this request.
Lang_decline_request: to decline this request.
Lang_request_expire_1: This request is only good for
Lang_request_expire_2: Seconds
Lang_request_expire_3: before it expires.
Lang_type: Type
Lang_no_active_request: No active request exist.
Lang_action_cooldown: This action is on cooldown.
...
